// Function declarations

void __cdecl main();
void __cdecl setup_start_vars();
int *__cdecl track_end_callback();
void __cdecl draw_elspa_screen();
void __cdecl init_hires_prim(struct DB *db);
void __cdecl load_in_panel();
void __cdecl setup_vram();
void __cdecl srm_last_draw_done();
void __cdecl swapscreen();
void __cdecl vbl_irq();
void __cdecl init_prim(struct DB *db);
void __cdecl set_split_draw_envs();
void __cdecl void_function();
void __cdecl setup_vecs(unsigned int sw, unsigned int ww, unsigned int wh);
int __cdecl JoystickRead(struct Joystick *joy);
void __cdecl JoystickRead2(struct Joystick *joy);
__int16 __cdecl GetJoyInfo(unsigned int control_mode);
unsigned __int16 *__cdecl loadTIM(unsigned int *addr);
void __cdecl srm_keep_the_clut(unsigned __int16 *source);
void __cdecl make_fade_tables(unsigned __int16 *source);
void __cdecl srm_DrawASprite(__int16 x, __int16 y, unsigned __int16 z, struct Sprite *sprite);
void __cdecl draw_octane_trans_sprite(__int16 x, __int16 y, struct Sprite *sprite);
void __cdecl WaitVbi();
void __cdecl srmCopyScreen();
void __cdecl DrawBoxBPP(int x, int y, int w, int h, int colour, int fx);
void __cdecl DrawBox(int x, int y, int w, int h, int colour);
void __cdecl PDrawBoxBPP(int x, int y, int w, int h, int colour, int fx);
void __cdecl srm_DrawScaleSprite(int x, int y, unsigned __int16 tnum);
void __cdecl srm_DrawScaleSpriteShadow(int x, int y, unsigned __int16 tnum);
int __cdecl draw_color_sprite(__int16 x, __int16 y, struct Sprite *sprite, unsigned __int8 colour);
void __cdecl force_text_cluts();
int __cdecl monitor_draw_color_sprite(__int16 x, __int16 y, struct Sprite *sprite, unsigned __int8 colour, int glass, int outline);
void __cdecl ResetTimer();
unsigned int __cdecl CheckTimer(unsigned int wait);
int __cdecl draw_octane_color_sprite(__int16 xpos, __int16 ypos, struct Sprite *t_sprite, unsigned __int8 colour, int exclude);
unsigned __int16 __cdecl fade_colour(unsigned __int16 final_col, unsigned __int16 start_col, unsigned __int16 pal_num, unsigned __int16 no_pals);
void __cdecl srm_DrawSky2();
void __cdecl srm_DrawSky(__int16 x, __int16 y);
int __cdecl initSystem();
int __cdecl initBG();
void __cdecl srm_load_sky(unsigned __int8 level_number);
void __cdecl screen_off();
void __cdecl screen_on();
void __cdecl drop_title_screen();
void __cdecl next_title_pos(__int16 ypos);
void __cdecl draw_game_logo2();
void __cdecl lift_screen();
void __cdecl game_draw_stack();
int __cdecl my_mkdir(char *directory_name);
void __cdecl game();
int __cdecl game_process();
int __cdecl game_setup();
int __cdecl control_process();
int __cdecl control_user_process(struct ControlUser *control_user);
int __cdecl control_setup(int player, int origin);
int __cdecl control_set_default_all();
int __cdecl control_reset_all();
int __cdecl control_count_active();
int __cdecl control_rating(struct Control *control);
void __cdecl object_setup();
int __cdecl initialiseOBJECT_SIGN_POST(struct Thing *thing);
int __cdecl processOBJECT_SIGN_POST(struct Thing *thing);
int __cdecl removeOBJECT_SIGN_POST(struct Thing *thing);
int __cdecl initialiseOBJECT_TREE(struct Thing *thing);
int __cdecl processOBJECT_TREE(struct Thing *thing);
int __cdecl removeOBJECT_TREE(struct Thing *thing);
int __cdecl initialiseOBJECT_LAMP_POST(struct Thing *thing);
int __cdecl processOBJECT_LAMP_POST(struct Thing *thing);
int __cdecl removeOBJECT_LAMP_POST(struct Thing *thing);
int __cdecl initialiseOBJECT_CAMERA_STATIC(struct Thing *thing);
int __cdecl processOBJECT_CAMERA_STATIC(struct Thing *thing);
int __cdecl removeOBJECT_CAMERA_STATIC(struct Thing *thing);
int __cdecl initialiseOBJECT_CAMERA_FOLLOW(struct Thing *thing);
int __cdecl processOBJECT_CAMERA_FOLLOW(struct Thing *thing);
int __cdecl removeOBJECT_CAMERA_FOLLOW(struct Thing *thing);
int __cdecl object_record_clone(struct Thing *thing);
int __cdecl object_copy_clone(struct Thing *thing);
int __cdecl object_play_clone(struct Thing *thing);
int __cdecl initialiseOBJECT_CLONE(struct Thing *thing);
int __cdecl processOBJECT_CLONE(struct Thing *thing);
int __cdecl removeOBJECT_CLONE(struct Thing *thing);
struct Thing *__cdecl object_colide_vehicle(struct Thing *thing);
void __cdecl object_init_cone(struct Thing *thing, unsigned __int16 object);
void __cdecl object_process_cone(struct Thing *thing);
int __cdecl initialiseOBJECT_CONE1(struct Thing *thing);
int __cdecl processOBJECT_CONE1(struct Thing *thing);
int __cdecl removeOBJECT_CONE1(struct Thing *thing);
int __cdecl initialiseOBJECT_CONE2(struct Thing *thing);
int __cdecl processOBJECT_CONE2(struct Thing *thing);
int __cdecl removeOBJECT_CONE2(struct Thing *thing);
int __cdecl initialiseOBJECT_BARREL1(struct Thing *thing);
int __cdecl processOBJECT_BARREL1(struct Thing *thing);
int __cdecl removeOBJECT_BARREL1(struct Thing *thing);
int __cdecl initialiseOBJECT_BARREL2(struct Thing *thing);
int __cdecl processOBJECT_BARREL2(struct Thing *thing);
int __cdecl removeOBJECT_BARREL2(struct Thing *thing);
int __cdecl initialiseOBJECT_BARREL3(struct Thing *thing);
int __cdecl processOBJECT_BARREL3(struct Thing *thing);
int __cdecl removeOBJECT_BARREL3(struct Thing *thing);
int __cdecl setup_object_stubs();
int __cdecl get_stub();
int __cdecl delete_stub(unsigned __int16 object_handle);
int __cdecl get_kframe();
int __cdecl delete_kframe(unsigned __int16 idx);
void __cdecl init_vecobj(struct M33 *v);
int __cdecl get_objvec();
int __cdecl delete_objvec(unsigned __int16 idx);
int __cdecl register_an_object(unsigned __int16 mode);
int __cdecl deallocate_object_handle(unsigned __int16 handle);
void __cdecl sequence_pause();
void __cdecl assign_sequence(unsigned __int16 squ_idx, unsigned __int16 *object_handle);
void __cdecl assign_frame(unsigned __int16 object, unsigned __int16 frame, unsigned __int16 *object_handle);
void __cdecl set_sequence_loop(unsigned __int16 object_handle);
void __cdecl tween_points(struct _111fake_duplicate_s2 *diffs, struct _108fake *object, unsigned __int16 current, unsigned __int16 next, int count);
void __cdecl animate_object(struct _100fake *kframer);
void __cdecl setup_object(struct _108fake *object, struct _112fake_duplicate_s1 *o_tab);
unsigned __int16 __cdecl load_object(unsigned __int8 *srm_obj_source, unsigned __int16 fsize);
void __cdecl trans_matrix(struct M33 *m1, struct M33 *m2);
void __cdecl rotate_point(struct _95fake *coord, struct M33 *matrix);
void __cdecl set_orientation(struct Thing *t_thing, unsigned __int16 angle, unsigned __int16 tilt, unsigned __int16 roll);
void __cdecl set_rotation(unsigned __int16 object_handle, __int16 angle, __int16 tilt, __int16 roll);
void __cdecl assign_test_object(struct Thing *t_thing);
void __cdecl assign_object(struct Thing *t_thing, unsigned __int16 object);
void __cdecl change_object(struct Thing *t_thing, unsigned __int16 object, unsigned __int16 col);
void __cdecl draw_object(struct _113fake *drawinfo);
void __cdecl do_object(unsigned __int16 object_handle, struct M33 *camera);
int __cdecl vehicle_checkpoint_distance(struct Thing *thing);
int __cdecl vehicle_colide_all_checkpoints(struct Thing *thing);
int __cdecl vehicle_checkpoint_colide_thing(struct Thing *checkpoint, struct Thing *thing);
int __cdecl vehicle_checkpoint_next_lap(struct Thing *thing);
int __cdecl vehicle_checkpoint_find_next(struct Thing *thing);
int __cdecl vehicle_checkpoint_find_previous(struct Thing *thing);
int __cdecl vehicle_process_checkpoint(struct Thing *thing, __int16 cp_colide);
int __cdecl vehicle_get_checkpoint(struct Thing *thing);
int __cdecl vehicle_get_checkpoint_old(struct Thing *thing);
int __cdecl vehicle_race_positions_compare(struct Thing *vehicle1, struct Thing *vehicle2);
int __cdecl vehicle_race_positions();
int __cdecl vehicle_process_autotarget(struct Thing *thing);
int __cdecl vehicle_target(struct Thing *thing, int angle);
int __cdecl vehicle_target_valid(struct Thing *thing, struct Thing *target, int angle, int range);
int __cdecl vehicle_target_valid_enemy_target(struct Thing *thing, int angle, int range);
int __cdecl vehicle_map_floor(struct Coord3D *position);
int __cdecl vehicle_check_vehicle_movement_status(struct Thing *thing);
int __cdecl vehicle_computer_set_no_shoot(struct Thing *thing);
int __cdecl vehicle_setup_computer_character(struct Thing *thing);
int __cdecl vehicle_any_target(struct Thing *thing, int angle, int range);
int __cdecl vehicle_set_autodrive_on(struct Thing *thing);
int __cdecl vehicle_set_autodrive_off(struct Thing *thing);
int __cdecl vehicle_set_autopilot_on(struct Thing *thing);
int __cdecl vehicle_set_autopilot_off(struct Thing *thing);
int __cdecl vehicle_control_computer(struct Thing *thing);
int __cdecl vehicle_targetting_system(struct Thing *thing);
int __cdecl vehicle_control_from_autopilot(struct Thing *thing);
int __cdecl vehicle_control_from_player(struct Thing *thing);
int __cdecl vehicle_control(struct Thing *thing);
void __cdecl collide_inelastic(struct Coord3D *pos1, struct Coord3D *pos2, struct Coord3D *u1, struct Coord3D *u2, struct Coord3D *v1, struct Coord3D *v2, struct Coord3D *bump);
__int16 __cdecl point_from_line(int x1, int y1, int dx, int dy, int px, int py);
int __cdecl collide_on_circle(struct Coord3D *center, struct Coord3D *pos, struct Coord3D *delta, __int16 radius, struct Coord3D *colision_point);
int __cdecl vehicle_colide(struct Thing *master_vehicle, struct Coord3D *delta);
int __cdecl vehicle_colide_final_check(struct Thing *master_vehicle, struct Coord3D *delta);
void __cdecl vehicle_sensor_point_process(struct Thing *thing, struct SensorPoint *sensor, struct Coord3D *slope, unsigned __int16 terrain);
void __cdecl vehicle_sensor_point_projection(struct Thing *thing, struct Coord3D *delta);
int __cdecl vector_modulus(struct Coord3D *vector);
void __cdecl vector_component_at_angle(struct Coord3D *result, struct Coord3D *vector, __int16 angle);
void __cdecl vehicle_setup_tumble(struct Thing *thing);
__int16 __cdecl vehicle_do_tumble(struct Thing *thing);
void __cdecl vehicle_colide_map(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_colide_vehicle(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_colide_vectors(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_move_tilt(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_move_roll(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_calculate_movement_delta(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_move_altitude(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_calculate_slope(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_calculate_thrust(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_do_action(struct Thing *thing);
void __cdecl vehicle_get_track_friction(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_calculate_angle(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_set_camera(struct Thing *thing);
void __cdecl vehicle_terrain_effect(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_move_mapwho(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_check_bonuses(struct Thing *thing);
void __cdecl vehicle_calculate_behind_factor(struct Thing *thing);
void __cdecl vehicle_post_process(struct Thing *thing);
void __cdecl vehicle_calculate_momentum(struct Thing *thing, struct Coord3D *delta);
void __cdecl vehicle_setup_difficulty_single_player(struct Control *control);
int __cdecl initialiseVEHICLE_CAR(struct Thing *thing);
int __cdecl processVEHICLE_CAR(struct Thing *thing);
int __cdecl removeVEHICLE_CAR(struct Thing *thing);
int __cdecl initialiseVEHICLE_TRAIN(struct Thing *thing);
int __cdecl processVEHICLE_TRAIN(struct Thing *thing);
int __cdecl removeVEHICLE_TRAIN(struct Thing *thing);
int __cdecl initialiseVEHICLE_PLANE(struct Thing *thing);
int __cdecl processVEHICLE_PLANE(struct Thing *thing);
int __cdecl removeVEHICLE_PLANE(struct Thing *thing);
int __cdecl initialiseVEHICLE_HELICOPTER(struct Thing *thing);
int __cdecl processVEHICLE_HELICOPTER(struct Thing *thing);
int __cdecl removeVEHICLE_HELICOPTER(struct Thing *thing);
int __cdecl initialiseVEHICLE_HOVER_BOARD(struct Thing *thing);
int __cdecl processVEHICLE_HOVER_BOARD(struct Thing *thing);
int __cdecl removeVEHICLE_HOVER_BOARD(struct Thing *thing);
int __cdecl initialiseVEHICLE_HOVER_BIKE(struct Thing *thing);
int __cdecl processVEHICLE_HOVER_BIKE(struct Thing *thing);
int __cdecl removeVEHICLE_HOVER_BIKE(struct Thing *thing);
int __cdecl initialiseVEHICLE_HOVER_CAR(struct Thing *thing);
int __cdecl processVEHICLE_HOVER_CAR(struct Thing *thing);
int __cdecl removeVEHICLE_HOVER_CAR(struct Thing *thing);
int __cdecl initialiseVEHICLE_HOVER_CRAFT(struct Thing *thing);
int __cdecl processVEHICLE_HOVER_CRAFT(struct Thing *thing);
int __cdecl removeVEHICLE_HOVER_CRAFT(struct Thing *thing);
int __cdecl initialiseVEHICLE_HOVER_JUGGER(struct Thing *thing);
int __cdecl processVEHICLE_HOVER_JUGGER(struct Thing *thing);
int __cdecl removeVEHICLE_HOVER_JUGGER(struct Thing *thing);
int __cdecl repair_vehicle_drop_point_ok(struct Thing *thing, unsigned __int16 waypoint);
int __cdecl repair_vehicle_search(struct Thing *thing);
int __cdecl repair_vehicle_rotate_car(struct Thing *thing, struct Thing *t_thing);
int __cdecl repair_vehicle_find_drop_waypoint(struct Thing *thing);
int __cdecl repair_vehicle_move_toward(struct Thing *thing, struct Coord3D *t_position, struct Coord3D *delta, int speed, int dist);
int __cdecl initialiseVEHICLE_POLICE_HELICOPTER(struct Thing *thing);
int __cdecl processVEHICLE_POLICE_HELICOPTER(struct Thing *thing);
int __cdecl removeVEHICLE_POLICE_HELICOPTER(struct Thing *thing);
int __cdecl initialiseVEHICLE_JOURNAL_HELICOPTER(struct Thing *thing);
int __cdecl processVEHICLE_JOURNAL_HELICOPTER(struct Thing *thing);
int __cdecl removeVEHICLE_JOURNAL_HELICOPTER(struct Thing *thing);
int __cdecl camera_setup(int camera_index);
int __cdecl camera_setup_split_screen(int camera_index);
int __cdecl camera_setup_all(int model);
int __cdecl camera_process_all(int model);
int __cdecl camera_scan_back(struct Coord3D *position_start, __int16 angle_xy, __int16 angle_zy, __int16 distance);
int __cdecl camera_process_position(struct Thing *thing, int camera_index, int distance, int degrees);
int __cdecl camera_process(int player_number, int force_camera_action, int camera_index);
void __cdecl make_scanner_map();
void __cdecl scanner();
int __cdecl packet_level_update_after_load();
int __cdecl packet_process();
int __cdecl packet_process_single(struct Packet *packet, struct Control *control);
int __cdecl packet_initialise_player(struct Control *control);
int __cdecl packet_log(int action, int data1, int data2);
int __cdecl packet_clear(struct Packet *packet);
int __cdecl packet_count_active();
int __cdecl packet_record();
int __cdecl packet_play();
int __cdecl packet_stop();
int __cdecl map_altitude_column_and_floor(struct Coord3D *position);
int __cdecl map_colide(struct Coord3D *position);
int __cdecl map_colide_4point(struct Coord3D *position, int size_x, int size_y);
int __cdecl map_colide_adjust_position(struct Coord3D *position, struct Coord3D *position_new, int steps);
int __cdecl map_colide_direction(struct Coord3D *old_position, struct Coord3D *new_position);
int __cdecl map_colide_direction_xy(struct Coord3D *old_position, struct Coord3D *new_position);
int __cdecl map_colide_direction_4point(struct Coord3D *old_position, struct Coord3D *new_position, int size_x, int size_y);
int __cdecl map_colide_distance_x(struct Coord3D *position, __int16 xpos, int sign);
int __cdecl map_colide_distance_y(struct Coord3D *position, __int16 ypos, int sign);
int __cdecl map_colide_distance_z(struct Coord3D *position, __int16 zpos, int sign);
int __cdecl map_colide_distance_xyz(struct Coord3D *position, __int16 angle_xy, __int16 angle_zy, int maximum_distance, int steps);
int __cdecl map_floor(struct Coord3D *position);
int __cdecl map_colide_column(struct Coord3D *position);
int __cdecl map_colide_with_affect(struct Coord3D *position);
int __cdecl map_block_number(struct Coord3D *position);
int __cdecl map_colide_type(struct Coord3D *position);
int __cdecl map_colide_friction(struct Coord3D *position);
int __cdecl map_altitude_lowest(struct Coord3D *position);
int __cdecl map_altitude_highest(struct Coord3D *position);
int __cdecl map_element_swap(int source_xpos, int source_ypos, int destination_xpos, int destination_ypos);
int __cdecl map_element_move(int source_xpos, int source_ypos, int destination_xpos, int destination_ypos);
int __cdecl map_element_copy(int source_xpos, int source_ypos, int destination_xpos, int destination_ypos);
int __cdecl map_element_remove(int destination_xpos, int destination_ypos);
int __cdecl map_element_morph(int source_xpos, int source_ypos, int destination_xpos, int destination_ypos);
int __cdecl map_column_add(struct Column *new_column);
int __cdecl map_column_copy(struct Column *new_column);
int __cdecl map_column_remove(int column_number, struct MapElement *map_element);
int __cdecl map_cube_add(struct Cube *new_cube);
int __cdecl map_cube_remove(int cube_number);
void __cdecl srm_first_load();
int __cdecl map_load_blocks_needed(int level_number);
int __cdecl map_fractal_altitude(int seed);
int __cdecl invalidate_back_points(union MapPosXY themap);
void __cdecl breakin();
void __cdecl copy_back_points_to_front_and_invalidate_back(union MapPosXY themap);
void __cdecl new_trig(struct _95fake *c0, struct _95fake *c1, struct _95fake *c2);
void __cdecl do_a_trig(struct _95fake *coord0, struct _95fake *coord1, struct _95fake *coord2, struct Reorient *reo, int srm_block);
void __cdecl do_a_plane_of_engine_columns(union MapPosXY themap, int apos, int bpos);
void __cdecl simple_sky();
void __cdecl create_fader();
void __cdecl find_gamut();
void __cdecl clear_draw_list();
void __cdecl psx_sky(__int16 x, __int16 y);
void __cdecl psx_sky_dark(__int16 x, __int16 y);
void __cdecl draw_view(struct Camera *camera, unsigned __int8 eye);
int __cdecl world_xyz_to_screen_xy(int *sx, int *sy, __int16 x, __int16 y, int z);
void __cdecl make_solidmask(struct Column *column);
int __cdecl collide_map(int xpos, int ypos);
void __cdecl draw_stack_camera();
void __cdecl engine(struct Camera *camera);
void __cdecl srm_trig(struct _95fake *coord0, struct _95fake *coord1, struct _95fake *coord2);
int __cdecl move_xyz(struct Coord3D *position, unsigned __int16 angle_xy, unsigned __int16 angle_zy, __int16 speed);
int __cdecl movement_xyz(struct Coord3D *position, struct Movement *movement);
int __cdecl move_displacement_set(struct Coord3D *position, unsigned __int16 angle_xy, unsigned __int16 angle_zy, __int16 speed);
int __cdecl move_displacement_xyz(struct Coord3D *position, struct Coord3D *displacement, int sign);
int __cdecl move_displacement_xyz_256(struct Coord3D *position, struct Coord3D *displacement, int sign);
int __cdecl move_displacement_slope(struct Coord3D *position, struct Coord3D *displacement);
int __cdecl move_increment_dampen(int number, int amount);
int __cdecl move_increment_fraction(int number, int multiplier, int divisor);
int __cdecl move_swap_positions(struct Coord3D *position1, struct Coord3D *position2);
int __cdecl move_point_see_point_steps(struct Coord3D *position, struct Coord3D *displacement, int maximum_steps);
int __cdecl move_point_see_point(struct Coord3D *position_from, struct Coord3D *position_to);
int __cdecl move_point_see_point_distance(struct Coord3D *position_from, struct Coord3D *position_to);
__int16 __cdecl angle_get_xy(struct Coord3D *position_from, struct Coord3D *position_to);
__int16 __cdecl angle_get_xy_relative(struct Coord3D *position);
__int16 __cdecl angle_get_zy(struct Coord3D *position_from, struct Coord3D *position_to);
int __cdecl angle_get_difference(__int16 angle1, __int16 angle2);
int __cdecl angle_get_sign(__int16 angle1, __int16 angle2);
int __cdecl angle_rotate_point(struct Coord3D *point, __int16 angle_xy, __int16 angle_zy);
unsigned int __cdecl distance_get_x(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_y(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_z(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_rough_xyz(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_rough_xy(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_xyz(struct Coord3D *position1, struct Coord3D *position2);
int __cdecl distance_set_xyz(struct Coord3D *distance, struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_squared_xyz(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_xy(struct Coord3D *position1, struct Coord3D *position2);
unsigned int __cdecl distance_get_squared_xy(struct Coord3D *position1, struct Coord3D *position2);
int __cdecl distance_snap_coordinates(struct Coord3D *position);
int __cdecl distance_get_xy_coords(struct Coord3D *position1, struct Coord3D *position2, struct Coord3D *distance);
int __cdecl distance_get_xyz_coords(struct Coord3D *position1, struct Coord3D *position2, struct Coord3D *distance);
int __cdecl thing_check_for_human_in_sight();
int __cdecl thing_make_group_list();
int __cdecl thing_initialise_list_setup();
int __cdecl thing_initialise_list_reset();
int __cdecl thing_initialise_level_setup();
int __cdecl thing_number_free();
int __cdecl thing_number_used();
int __cdecl thing_set_colide_size(struct Thing *thing, int draw_number, int size_x, int size_y, int size_z);
int __cdecl thing_set_colide_attrib(struct Thing *thing, int group);
int __cdecl thing_set_defaults(struct Thing *thing);
int __cdecl thing_set_draw(struct Thing *thing, int number);
int __cdecl thing_set_draw_vector(struct Thing *thing, int number);
struct Thing *__cdecl thing_get_vacant();
struct Thing *__cdecl thing_initialise_member(struct Coord3D *position, struct Angle *angle, int group, int member, int id);
struct Thing *__cdecl thing_initialise(struct Coord3D *position, struct Angle *angle, int group, int member, int id);
int __cdecl thing_process_member(struct Thing *thing);
int __cdecl thing_process(struct Thing *thing);
int __cdecl thing_process_all();
int __cdecl thing_remove_member(struct Thing *thing);
int __cdecl thing_remove(struct Thing *thing);
int __cdecl thing_delete(struct Thing *thing);
int __cdecl thing_overlapping(struct Thing *thing1, struct Thing *thing2);
int __cdecl thing_overlapping_building(struct Thing *thing, struct Thing *building);
int __cdecl thing_check_mapwho_cell(struct Thing *thing, struct Thing *touching_thing);
int __cdecl thing_touching_anything(struct Thing *thing);
int __cdecl thing_animate(struct Thing *thing);
int __cdecl thing_set_action(struct Thing *thing, __int16 action);
int __cdecl thing_initialise_edited_list(int switch_id);
unsigned __int8 __cdecl open_tmap_data_file();
int __cdecl load_tmap_at(unsigned __int16 idx, unsigned __int8 *buf);
unsigned __int8 __cdecl remove_tmap_group_from_heap(unsigned __int16 idx);
unsigned __int8 __cdecl remove_tmap_group_from_heap_even_permanent(unsigned __int16 idx);
unsigned int __cdecl tmap_group_size(unsigned __int16 idx);
void __cdecl add_tmap_group_to_heap(unsigned __int16 idx);
unsigned int __cdecl heap_free(unsigned int size);
void __cdecl setup_rotate_stuff(int x, int y, int z, int fade_max, int fade_min, int lens, int angle, int roll);
void __cdecl do_map_who(__int16 who);
unsigned int __cdecl SqrL(unsigned int x);
void __cdecl matrix_transform(struct M31 *result, struct M33 *trans, struct M31 *source);
void __cdecl matrix_transform33(struct M33 *result, struct M33 *trans, struct M33 *source);
void __cdecl object_vec_normalisation(struct M33 *vec, unsigned __int8 col);
void __cdecl vec_cross_prod(struct M31 *result, struct M31 *vec1, struct M31 *vec2);
void __cdecl rotate_object_axis(struct M33 *base, __int16 xangle, __int16 yangle, __int16 zangle);
void __cdecl rotate_obj(__int16 xangle, __int16 yangle, __int16 zangle, struct M33 *r3);
void __cdecl rotate_on_x(__int16 angle, struct M33 *matrix);
void __cdecl rotate_on_y(__int16 angle, struct M33 *matrix);
void __cdecl rotate_on_z(__int16 angle, struct M33 *matrix);
void __cdecl base_vec_normalisation(struct M33 *vec, unsigned __int8 row);
void __cdecl rotate_base_axis(struct M33 *base, __int16 theta, unsigned __int8 flag);
// struct AnimPageDynamic *__cdecl DynAnimBankAddPage(struct AnimPageDynamicBank *anim_bank, struct ScaleSprite **sprite, unsigned __int16 id);
void __cdecl DynAnimBankDeletePage(struct AnimPageDynamic *page);
void __cdecl DynAnimBankDeleteAllPage(struct AnimPageDynamicBank *anim_bank);
void __cdecl DynAnimBankDeactivateAllPage(struct AnimPageDynamicBank *anim_bank);
void __cdecl DynAnimBankDeactivatePage(struct AnimPageDynamic *page);
void __cdecl DynAnimBankTogleActivatePage(struct AnimPageDynamic *page);
struct AnimPageDynamic *__cdecl DynAnimBankID2Ptr(struct AnimPageDynamicBank *anim_bank, unsigned __int16 id);
void __cdecl DynAnimBankActivatePage(struct AnimPageDynamic *page);
unsigned __int8 *__cdecl HeapDataPtr(struct Heap *heap, __int16 handle);
unsigned int __cdecl HeapHandleExists(struct Heap *heap, __int16 handle);
struct HeapHandle *__cdecl HeapAdd(struct Heap *heap, unsigned __int8 *source, unsigned int size, unsigned __int16 id);
unsigned int __cdecl HeapFreeSpace(struct Heap *heap);
struct HeapHandle *__cdecl HeapCreate(struct Heap *heap, unsigned int size, unsigned __int16 id);
void __cdecl HeapDelete(struct Heap *heap, struct HeapHandle *hh);
void __cdecl HeapDeleteAll(struct Heap *heap);
struct HeapHandle *__cdecl HeapID2Handle(struct Heap *heap, unsigned __int16 id);
void __cdecl HeapDone(struct Heap **heap);
void __cdecl JoystickReInit(struct Joystick *joy);
void __cdecl JoystickInit(struct Joystick *joy, unsigned __int8 joytype);
unsigned __int8 __cdecl FindColor(void *palette, unsigned __int8 rr, unsigned __int8 gg, unsigned __int8 bb);
int __cdecl arctan(__int16 x, __int16 y);
void __cdecl set_colour(unsigned __int8 col, unsigned __int8 red, unsigned __int8 green, unsigned __int8 blue);
void __cdecl init_track_vectors();
void __cdecl add_collision_to_single_mapwho(unsigned __int16 x, unsigned __int16 y);
void __cdecl insert_vect(unsigned __int16 x1, unsigned __int16 y1, unsigned __int16 z1, unsigned __int16 x2, int y2, int z2);
unsigned __int8 __cdecl two4_line_intersection(int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4);
unsigned __int8 __cdecl do_move_colide(unsigned __int16 x1, unsigned __int16 y1, unsigned __int16 x2, unsigned __int16 y2, struct MapElement *me);
unsigned __int16 __cdecl track_vector_collide(struct Coord3D *position1, struct Coord3D *position2);
int __cdecl initialiseTRACK_VECTOR(struct Thing *thing);
int __cdecl processTRACK_VECTOR(struct Thing *thing);
int __cdecl removeTRACK_VECTOR(struct Thing *thing);
void __cdecl track_init_all_waypoints();
int __cdecl track_new_waypoint();
int __cdecl track_waypoint_junction_exists(int point, __int16 wp_type);
int __cdecl track_waypoint_junction(int point);
int __cdecl track_waypoint_nearest(struct Thing *thing);
int __cdecl track_waypoint_absolute_nearest(struct Thing *thing);
int __cdecl track_waypoint_colide_area(struct Thing *thing);
int __cdecl track_waypoint_distance(struct Coord3D *position, int waypoint);
int __cdecl track_waypoint_position_set(struct Coord3D *position, int waypoint);
int __cdecl track_waypoint_type(int waypoint);
int __cdecl track_waypoint_child(int waypoint);
int __cdecl track_waypoint_exists(__int16 x1, __int16 y1);
int __cdecl track_initialise_waypoint(unsigned __int16 wp_type, unsigned __int16 x1, unsigned __int16 y1, unsigned __int16 x2, int y2);
int __cdecl initialiseTRACK_WAY_POINT(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_FUEL(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_FUEL(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_FUEL(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_WEAPONS(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_WEAPONS(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_WEAPONS(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_ARMOUR(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_ARMOUR(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_ARMOUR(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_STOP(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_STOP(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_STOP(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_SHORT_CUT(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_SHORT_CUT(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_SHORT_CUT(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_CAVE_START(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_CAVE_START(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_CAVE_START(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_BRAKE(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_BRAKE(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_BRAKE(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_NO_BOOST(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_NO_BOOST(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_NO_BOOST(struct Thing *thing);
int __cdecl initialiseTRACK_WAY_POINT_FULL_BOOST(struct Thing *thing);
int __cdecl processTRACK_WAY_POINT_FULL_BOOST(struct Thing *thing);
int __cdecl removeTRACK_WAY_POINT_FULL_BOOST(struct Thing *thing);
int __cdecl effect_affect_vehicle_exclusive(struct Thing *effect);
int __cdecl initialiseEFFECT_EXPLOSION(struct Thing *thing);
int __cdecl processEFFECT_EXPLOSION(struct Thing *thing);
int __cdecl removeEFFECT_EXPLOSION(struct Thing *thing);
int __cdecl initialiseEFFECT_EXPLOSION_MEDIUM(struct Thing *thing);
int __cdecl processEFFECT_EXPLOSION_MEDIUM(struct Thing *thing);
int __cdecl removeEFFECT_EXPLOSION_MEDIUM(struct Thing *thing);
int __cdecl initialiseEFFECT_EXPLOSION_BIG(struct Thing *thing);
int __cdecl processEFFECT_EXPLOSION_BIG(struct Thing *thing);
int __cdecl removeEFFECT_EXPLOSION_BIG(struct Thing *thing);
int __cdecl initialiseEFFECT_EXPLOSION_MASSIVE(struct Thing *thing);
int __cdecl processEFFECT_EXPLOSION_MASSIVE(struct Thing *thing);
int __cdecl removeEFFECT_EXPLOSION_MASSIVE(struct Thing *thing);
int __cdecl initialiseEFFECT_BULLET(struct Thing *thing);
int __cdecl processEFFECT_BULLET(struct Thing *thing);
int __cdecl removeEFFECT_BULLET(struct Thing *thing);
int __cdecl initialiseEFFECT_FIRE(struct Thing *thing);
int __cdecl processEFFECT_FIRE(struct Thing *thing);
int __cdecl removeEFFECT_FIRE(struct Thing *thing);
int __cdecl initialiseEFFECT_HOLE(struct Thing *thing);
int __cdecl processEFFECT_HOLE(struct Thing *thing);
int __cdecl removeEFFECT_HOLE(struct Thing *thing);
int __cdecl initialiseEFFECT_SMOKE(struct Thing *thing);
int __cdecl processEFFECT_SMOKE(struct Thing *thing);
int __cdecl removeEFFECT_SMOKE(struct Thing *thing);
int __cdecl initialiseEFFECT_SMOKE_FIRE(struct Thing *thing);
int __cdecl processEFFECT_SMOKE_FIRE(struct Thing *thing);
int __cdecl removeEFFECT_SMOKE_FIRE(struct Thing *thing);
int __cdecl initialiseEFFECT_LIGHT(struct Thing *thing);
int __cdecl processEFFECT_LIGHT(struct Thing *thing);
int __cdecl removeEFFECT_LIGHT(struct Thing *thing);
int __cdecl initialiseEFFECT_EARTHQUAKE(struct Thing *thing);
int __cdecl processEFFECT_EARTHQUAKE(struct Thing *thing);
int __cdecl removeEFFECT_EARTHQUAKE(struct Thing *thing);
int __cdecl initialiseEFFECT_TREMOR(struct Thing *thing);
int __cdecl processEFFECT_TREMOR(struct Thing *thing);
int __cdecl removeEFFECT_TREMOR(struct Thing *thing);
int __cdecl initialiseEFFECT_GAS(struct Thing *thing);
int __cdecl processEFFECT_GAS(struct Thing *thing);
int __cdecl removeEFFECT_GAS(struct Thing *thing);
int __cdecl initialiseEFFECT_ALTITUDE(struct Thing *thing);
int __cdecl processEFFECT_ALTITUDE(struct Thing *thing);
int __cdecl removeEFFECT_ALTITUDE(struct Thing *thing);
int __cdecl initialiseEFFECT_SHADE(struct Thing *thing);
int __cdecl processEFFECT_SHADE(struct Thing *thing);
int __cdecl removeEFFECT_SHADE(struct Thing *thing);
int __cdecl initialiseEFFECT_MOVE_AREA(struct Thing *thing);
int __cdecl processEFFECT_MOVE_AREA(struct Thing *thing);
int __cdecl removeEFFECT_MOVE_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_SWAP_AREA(struct Thing *thing);
int __cdecl processEFFECT_SWAP_AREA(struct Thing *thing);
int __cdecl removeEFFECT_SWAP_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_COPY_AREA(struct Thing *thing);
int __cdecl processEFFECT_COPY_AREA(struct Thing *thing);
int __cdecl removeEFFECT_COPY_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_REMOVE_AREA(struct Thing *thing);
int __cdecl processEFFECT_REMOVE_AREA(struct Thing *thing);
int __cdecl removeEFFECT_REMOVE_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_MARK_AREA(struct Thing *thing);
int __cdecl processEFFECT_MARK_AREA(struct Thing *thing);
int __cdecl removeEFFECT_MARK_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_SAND(struct Thing *thing);
int __cdecl processEFFECT_SAND(struct Thing *thing);
int __cdecl removeEFFECT_SAND(struct Thing *thing);
int __cdecl initialiseEFFECT_WATER(struct Thing *thing);
int __cdecl processEFFECT_WATER(struct Thing *thing);
int __cdecl removeEFFECT_WATER(struct Thing *thing);
int __cdecl initialiseEFFECT_FLARE(struct Thing *thing);
int __cdecl processEFFECT_FLARE(struct Thing *thing);
int __cdecl removeEFFECT_FLARE(struct Thing *thing);
int __cdecl initialiseEFFECT_MORPH_AREA(struct Thing *thing);
int __cdecl processEFFECT_MORPH_AREA(struct Thing *thing);
int __cdecl removeEFFECT_MORPH_AREA(struct Thing *thing);
int __cdecl initialiseEFFECT_MORPH_ALTITUDE(struct Thing *thing);
int __cdecl processEFFECT_MORPH_ALTITUDE(struct Thing *thing);
int __cdecl removeEFFECT_MORPH_ALTITUDE(struct Thing *thing);
int __cdecl initialiseEFFECT_MINE(struct Thing *thing);
int __cdecl processEFFECT_MINE(struct Thing *thing);
int __cdecl removeEFFECT_MINE(struct Thing *thing);
int __cdecl initialiseBUILDING_HOUSE(struct Thing *thing);
int __cdecl processBUILDING_HOUSE(struct Thing *thing);
int __cdecl removeBUILDING_HOUSE(struct Thing *thing);
int __cdecl initialiseBUILDING_REPAIR(struct Thing *thing);
int __cdecl processBUILDING_REPAIR(struct Thing *thing);
int __cdecl removeBUILDING_REPAIR(struct Thing *thing);
int __cdecl initialiseBUILDING_REFUEL(struct Thing *thing);
int __cdecl processBUILDING_REFUEL(struct Thing *thing);
int __cdecl removeBUILDING_REFUEL(struct Thing *thing);
int __cdecl initialiseBUILDING_REARM(struct Thing *thing);
int __cdecl processBUILDING_REARM(struct Thing *thing);
int __cdecl removeBUILDING_REARM(struct Thing *thing);
int __cdecl initialiseBUILDING_START(struct Thing *thing);
int __cdecl processBUILDING_START(struct Thing *thing);
int __cdecl removeBUILDING_START(struct Thing *thing);
int __cdecl initialiseBUILDING_CHECK_POINT(struct Thing *thing);
int __cdecl processBUILDING_CHECK_POINT(struct Thing *thing);
int __cdecl removeBUILDING_CHECK_POINT(struct Thing *thing);
int __cdecl powerup_init(struct Thing *thing);
int __cdecl powerup_move(struct Thing *thing);
int __cdecl initialisePOWERUP_INVINCABLE(struct Thing *thing);
int __cdecl processPOWERUP_INVINCABLE(struct Thing *thing);
int __cdecl removePOWERUP_INVINCABLE(struct Thing *thing);
int __cdecl initialisePOWERUP_INVISIBLE(struct Thing *thing);
int __cdecl processPOWERUP_INVISIBLE(struct Thing *thing);
int __cdecl removePOWERUP_INVISIBLE(struct Thing *thing);
int __cdecl initialisePOWERUP_HEALTH_EXTRA(struct Thing *thing);
int __cdecl processPOWERUP_HEALTH_EXTRA(struct Thing *thing);
int __cdecl removePOWERUP_HEALTH_EXTRA(struct Thing *thing);
int __cdecl initialisePOWERUP_HEALTH_FULL(struct Thing *thing);
int __cdecl processPOWERUP_HEALTH_FULL(struct Thing *thing);
int __cdecl removePOWERUP_HEALTH_FULL(struct Thing *thing);
int __cdecl initialisePOWERUP_HEALTH_DOUBLE(struct Thing *thing);
int __cdecl processPOWERUP_HEALTH_DOUBLE(struct Thing *thing);
int __cdecl removePOWERUP_HEALTH_DOUBLE(struct Thing *thing);
int __cdecl initialisePOWERUP_ENERGY_EXTRA(struct Thing *thing);
int __cdecl processPOWERUP_ENERGY_EXTRA(struct Thing *thing);
int __cdecl removePOWERUP_ENERGY_EXTRA(struct Thing *thing);
int __cdecl initialisePOWERUP_ENERGY_FULL(struct Thing *thing);
int __cdecl processPOWERUP_ENERGY_FULL(struct Thing *thing);
int __cdecl removePOWERUP_ENERGY_FULL(struct Thing *thing);
int __cdecl initialisePOWERUP_ENERGY_DOUBLE(struct Thing *thing);
int __cdecl processPOWERUP_ENERGY_DOUBLE(struct Thing *thing);
int __cdecl removePOWERUP_ENERGY_DOUBLE(struct Thing *thing);
int __cdecl initialisePOWERUP_FUEL_EXTRA(struct Thing *thing);
int __cdecl processPOWERUP_FUEL_EXTRA(struct Thing *thing);
int __cdecl removePOWERUP_FUEL_EXTRA(struct Thing *thing);
int __cdecl initialisePOWERUP_FUEL_FULL(struct Thing *thing);
int __cdecl processPOWERUP_FUEL_FULL(struct Thing *thing);
int __cdecl removePOWERUP_FUEL_FULL(struct Thing *thing);
int __cdecl initialisePOWERUP_FUEL_DOUBLE(struct Thing *thing);
int __cdecl processPOWERUP_FUEL_DOUBLE(struct Thing *thing);
int __cdecl removePOWERUP_FUEL_DOUBLE(struct Thing *thing);
int __cdecl initialisePOWERUP_MINI_GUN(struct Thing *thing);
int __cdecl processPOWERUP_MINI_GUN(struct Thing *thing);
int __cdecl removePOWERUP_MINI_GUN(struct Thing *thing);
int __cdecl initialisePOWERUP_ROCKET_GUN(struct Thing *thing);
int __cdecl processPOWERUP_ROCKET_GUN(struct Thing *thing);
int __cdecl removePOWERUP_ROCKET_GUN(struct Thing *thing);
int __cdecl initialisePOWERUP_BOOSTER(struct Thing *thing);
int __cdecl processPOWERUP_BOOSTER(struct Thing *thing);
int __cdecl removePOWERUP_BOOSTER(struct Thing *thing);
int __cdecl shot_touching_vehicle(struct Thing *shot, struct Coord3D *position);
int __cdecl initialiseSHOT_BULLET(struct Thing *thing);
int __cdecl processSHOT_BULLET(struct Thing *thing);
int __cdecl removeSHOT_BULLET(struct Thing *thing);
int __cdecl initialiseSHOT_BULLET_TRACER(struct Thing *thing);
int __cdecl processSHOT_BULLET_TRACER(struct Thing *thing);
int __cdecl removeSHOT_BULLET_TRACER(struct Thing *thing);
int __cdecl initialiseSHOT_BULLET_EXPLODE(struct Thing *thing);
int __cdecl processSHOT_BULLET_EXPLODE(struct Thing *thing);
int __cdecl removeSHOT_BULLET_EXPLODE(struct Thing *thing);
int __cdecl initialiseSHOT_MISSILE(struct Thing *thing);
int __cdecl processSHOT_MISSILE(struct Thing *thing);
int __cdecl removeSHOT_MISSILE(struct Thing *thing);
int __cdecl initialiseSWITCH_BOUNDARY(struct Thing *thing);
int __cdecl processSWITCH_BOUNDARY(struct Thing *thing);
int __cdecl removeSWITCH_BOUNDARY(struct Thing *thing);
int __cdecl initialiseSWITCH_TIMER(struct Thing *thing);
int __cdecl processSWITCH_TIMER(struct Thing *thing);
int __cdecl removeSWITCH_TIMER(struct Thing *thing);
int __cdecl initialiseSWITCH_ACTION(struct Thing *thing);
int __cdecl processSWITCH_ACTION(struct Thing *thing);
int __cdecl removeSWITCH_ACTION(struct Thing *thing);
int __cdecl initialiseSWITCH_ON_EFFECT(struct Thing *thing);
int __cdecl processSWITCH_ON_EFFECT(struct Thing *thing);
int __cdecl removeSWITCH_ON_EFFECT(struct Thing *thing);
int __cdecl initialiseWEATHER_WIND(struct Thing *thing);
int __cdecl processWEATHER_WIND(struct Thing *thing);
int __cdecl removeWEATHER_WIND(struct Thing *thing);
int __cdecl initialiseWEATHER_RAIN(struct Thing *thing);
int __cdecl processWEATHER_RAIN(struct Thing *thing);
int __cdecl removeWEATHER_RAIN(struct Thing *thing);
int __cdecl initialiseWEATHER_SNOW(struct Thing *thing);
int __cdecl processWEATHER_SNOW(struct Thing *thing);
int __cdecl removeWEATHER_SNOW(struct Thing *thing);
int __cdecl initialiseWEAPON_UZI(struct Thing *thing);
int __cdecl processWEAPON_UZI(struct Thing *thing);
int __cdecl removeWEAPON_UZI(struct Thing *thing);
int __cdecl initialiseWEAPON_MINI_GUN(struct Thing *thing);
int __cdecl processWEAPON_MINI_GUN(struct Thing *thing);
int __cdecl removeWEAPON_MINI_GUN(struct Thing *thing);
int __cdecl initialiseWEAPON_ROCKET_GUN(struct Thing *thing);
int __cdecl processWEAPON_ROCKET_GUN(struct Thing *thing);
int __cdecl removeWEAPON_ROCKET_GUN(struct Thing *thing);
int __cdecl initialiseWEAPON_BOOSTER(struct Thing *thing);
int __cdecl processWEAPON_BOOSTER(struct Thing *thing);
int __cdecl removeWEAPON_BOOSTER(struct Thing *thing);
int __cdecl mapwho_move(struct Thing *thing, struct Coord3D *position);
int __cdecl mapwho_add(struct Thing *thing, struct Coord3D *position);
int __cdecl mapwho_delete(struct Thing *thing);
int __cdecl mapwho_colide_marker_add(struct Thing *thing);
int __cdecl mapwho_colide_marker_delete(struct Thing *thing);
int __cdecl mapwho_colide_marker_increment(struct Thing *thing, int direction);
int __cdecl mapwho_colide_marker_test(struct Thing *thing);
int __cdecl mapwho_clear();
int __cdecl affect_thing(struct Thing *thing);
int __cdecl search_setup();
struct Coord3D *__cdecl search_start_cell(int start, int stop);
struct Coord3D *__cdecl search_start_level(int start, int stop);
struct Coord3D *__cdecl search_next();
int __cdecl search_stop();
int __cdecl person_control_from_player(struct Thing *thing);
int __cdecl initialisePERSON_PRESIDENT(struct Thing *thing);
int __cdecl processPERSON_PRESIDENT(struct Thing *thing);
int __cdecl removePERSON_PRESIDENT(struct Thing *thing);
int __cdecl initialiseSUPER_ANIMAL(struct Thing *thing);
int __cdecl processSUPER_ANIMAL(struct Thing *thing);
int __cdecl removeSUPER_ANIMAL(struct Thing *thing);
int __cdecl game_shimmer(struct Thing *thing);
int __cdecl draw_lights(int sprite1, int sprite2, int sprite3);
int __cdecl game_draw();
int __cdecl draw_setup_warning_text();
int __cdecl draw_set_warning_text(int number, struct Thing *thing);
int __cdecl draw_set_warning_text2(int number, struct Thing *thing);
int __cdecl draw_display_warning_text(struct Thing *thing);
int __cdecl draw_display_warning_text2(struct Thing *thing);
int __cdecl draw_show_control_name(char *string, int xpos, int ypos, int sprite_start);
int __cdecl draw_control_name_length(char *string, int xpos, int ypos, int sprite_start);
void __cdecl draw_make_warning_text(struct Control *view);
int __cdecl draw_panel(struct Control *view);
int __cdecl draw_panel2(struct Control *view);
int __cdecl draw_project(struct Control *view);
void __cdecl print_profile(int time, unsigned __int16 y);
int __cdecl level_load(int level_number);
void __cdecl Init_CD_ROM();
int __cdecl read_in_file(unsigned __int8 *buffer, unsigned __int8 *name);
int __cdecl screens_process(int network, int new_game);
unsigned __int8 __cdecl process_name_entry();
void __cdecl process_menu_screen(unsigned __int8 network);
void __cdecl process_language_select();
unsigned __int8 __cdecl process_select_track();
unsigned __int8 __cdecl process_select_car();
void __cdecl setup_options();
void __cdecl load_option_background();
void __cdecl setup_option_object_info();
void __cdecl setup_selects_track();
void __cdecl setup_selects_car();
void __cdecl reset_option_object_info();
void __cdecl reset_options();
void __cdecl setup_menu_screen();
void __cdecl change_rolling_demo();
void __cdecl setup_camera();
void __cdecl poly_setup_object_handle(struct OptionObj *myobj, unsigned __int16 object_no);
void __cdecl set_object_rotation(struct OptionObj *myobj);
void __cdecl poly_draw_object(struct OptionObj *myobj);
void __cdecl setup_draw_object();
void __cdecl DrawOptionObject(struct OptionObj *myobj);
void __cdecl scroll_option_vector(struct OptionObj *myobj, __int16 currentnumber, __int16 max_no_obj, __int16 scrollcount, int zoff);
unsigned __int8 __cdecl draw_and_edit_text(char *text, char *text_pos, unsigned __int8 str_len, __int16 xpos, int ypos, int justify);
unsigned __int8 __cdecl enter_name(char *text, unsigned __int8 string_length, char *text_position);
unsigned __int8 __cdecl check_for_quit_game();
int __cdecl waiting_for_players();
void __cdecl draw_network_count(int time);
void __cdecl draw_player_details(int player_number);
int __cdecl draw_attempting_connection(int m);
void __cdecl setup_grid_art();
void __cdecl draw_car_at_pos(__int16 x, __int16 y, __int16 z, __int16 angle, int tilt, int roll, int mylens, int number, int colour);
void __cdecl inkey_joystick();
void __cdecl draw_loading_level();
void __cdecl draw_current_track_info(__int16 *text_count);
void __cdecl draw_current_car_info(__int16 *text_count);
unsigned __int16 __cdecl digi_string_copy(char *src, char *dst, unsigned __int16 from, unsigned __int16 max);
void __cdecl setup_first_time_values();
void __cdecl process_hiscore();
void __cdecl draw_game_logo();
void __cdecl reward_screen();
void __cdecl draw_option_menu(struct OptionMenu *myoption, __int16 ypos, __int16 height);
unsigned __int8 __cdecl process_option_menu(struct OptionMenu *myoption);
void __cdecl setup_menu_strings();
void __cdecl toggle_shading();
void __cdecl toggle_sky();
void __cdecl toggle_texture_mapping();
void __cdecl set_login_on();
void __cdecl set_p2();
void __cdecl set_p3();
void __cdecl set_p4();
void __cdecl set_p5();
void __cdecl set_p6();
void __cdecl set_p7();
void __cdecl set_p8();
void __cdecl set_joystick();
void __cdecl change_no_players();
void __cdecl change_session_no();
void __cdecl change_num_lives();
void __cdecl change_clone_lap();
void __cdecl change_num_tag_players();
void __cdecl change_tag_race_time();
void __cdecl change_difficulty();
void __cdecl change_music_volume();
void __cdecl change_sample_volume();
void __cdecl srm_abort_game();
void __cdecl clear_high_scores();
void __cdecl toggle_network();
void __cdecl single_race_start();
void __cdecl championship_start();
void __cdecl clone_race_start();
void __cdecl death_match_start();
void __cdecl tag_race_start();
void __cdecl split_start();
void __cdecl quit_to_dos();
void __cdecl add_chars(char *string, char mychar, unsigned __int16 amount);
void __cdecl set_res_low();
void __cdecl set_res_high();
void __cdecl continue_championship();
void __cdecl new_championship();
void __cdecl quit_championship();
void __cdecl process_load_game();
void __cdecl process_save_game();
void __cdecl select_language_english();
void __cdecl select_language_french();
void __cdecl select_language_german();
void __cdecl select_language_spanish();
void __cdecl select_language_italian();
unsigned __int8 __cdecl draw_monitor(__int16 x, __int16 y, __int16 width, __int16 height);
void __cdecl draw_monitor_on_a_screen(__int16 x, __int16 y, __int16 width, __int16 height);
int __cdecl setup_in_game_options();
int __cdecl process_in_game_options();
int __cdecl draw_in_game_options();
void __cdecl clear_menus();
void __cdecl clear_menu(struct OptionMenu *mymenu);
void __cdecl setup_champ_menu();
void __cdecl set_monitor_off_screen(unsigned __int8 where);
void __cdecl set_monitor_reset();
unsigned __int8 __cdecl AskIfShouldFormat(unsigned __int8 card_number);
unsigned __int8 __cdecl AskIfShouldDelete(int SRM_CARD_NUM);
int __cdecl process_stats();
void __cdecl process_stats_screen();
void __cdecl process_points_table();
void __cdecl process_championship_table();
void __cdecl process_race_team_table();
void __cdecl process_end_of_championship();
void __cdecl wait_for_player_click();
int __cdecl calculate_best_lap(unsigned int player_number);
void __cdecl update_track_records();
void __cdecl calculate_points();
void __cdecl decalculate_points();
unsigned __int16 __cdecl calculate_longest_stats_string(char *text, char *text2, char *text3, char *text4);
void __cdecl add_hiscore();
void __cdecl check_and_add_score(unsigned __int16 player);
void __cdecl add_score(unsigned __int16 player, unsigned __int16 offset);
int __cdecl print_text(char *string, __int16 x, __int16 y, unsigned __int8 colour);
int __cdecl string_length(char *string);
int __cdecl character_width(char character);
int __cdecl character_height(char character);
int __cdecl set_userfont(__int16 font_number);
int __cdecl octane_text(char *string, __int16 x, __int16 y, char squash, int justify, int colour, int exclude);
int __cdecl octane_string_length(char *string, char squash);
int __cdecl octane_character_width(char character, char squash);
int __cdecl octane_character_height(char character);
int __cdecl monitor_text(char *string, __int16 x, __int16 y, __int16 squash);
int __cdecl monitor_string_length(char *string, __int16 squash);
int __cdecl monitor_character_count(char *string);
void __cdecl monitor_sort_text(char *text, __int16 count, __int16 max_count);
char *__cdecl monitor_strncopy(char *dst, char *src, __int16 n, unsigned __int8 *cr);
__int16 __cdecl myatoi(unsigned __int8 *ptr);
__int16 __cdecl OpenMusic(unsigned __int8 *midi_file, unsigned __int8 *midi_drvr, unsigned __int16 sound_irq, unsigned __int16 sound_dma, int sound_io);
void __cdecl CloseMusic();
void __cdecl SetMusicTempo(int percentage);
void __cdecl SetCDVolume();
void __cdecl StopMusic();
void __cdecl srm_StopMusic();
void __cdecl FadeOutMusic();
void __cdecl DoMusic();
void __cdecl srm_StartMusic(char sequence);
void __cdecl StartMusicFadeIn(char sequence);
void __cdecl RegisterSequence(int sequence);
void __cdecl Pause_Music();
void __cdecl UNPause_Music();
__int16 __cdecl SetupSound(unsigned __int16 parm1, unsigned __int16 parm2, unsigned __int16 parm3);
void __cdecl ResetSound();
void __cdecl FormatSounds();
void __cdecl FreeSounds();
int __cdecl libraryPlaySample(int source_id, int sample_number, int volume, int pan, int pitch, int loop, int type);
void __cdecl PlaySample2(int source_id, __int16 number, int volume, int pan, int pitch, int loop);
void __cdecl StartSample(__int16 channel, __int16 number, int volume, int pan, int pitch, int loop);
void __cdecl PlayActualSample(__int16 Channel, __int16 SampleNumber);
void __cdecl PlaySampleAndLoop(__int16 Channel, __int16 SampleNumber, __int16 blah);
void __cdecl PlayDifferentSample(int source_id, char sample_number, int volume, int pan, int pitch, int loop);
void __cdecl StopSample(int source_id, __int16 sample_number);
int __cdecl sample_stop(struct Thing *thing, __int16 number);
void __cdecl StopSound();
int __cdecl sample_play(struct Thing *thing, __int16 number);
int __cdecl sample_get_pitch(struct Thing *thing);
int __cdecl sample_get_volume(struct Thing *thing);
int __cdecl sample_get_pan(struct Thing *thing);
int __cdecl sample_play_or_adjust(int id, int number, int volume, int pan, int pitch, int loop, int type);
void __cdecl SetSamplePan(__int16 source_id, __int16 sample_number, unsigned __int16 pan);
void __cdecl SetSamplePitch(__int16 source_id, __int16 sample_number, int pitch);
void __cdecl SetSampleVolume(__int16 source_id, __int16 sample_number, int volume);
int __cdecl sample_scale_volume(int volume);
int __cdecl sample_set_pitch(struct Thing *thing, __int16 number, int pitch);
int __cdecl sample_set_volume(struct Thing *thing, __int16 number, int volume);
int __cdecl sample_set_pan(struct Thing *thing, __int16 number, int pan);
int __cdecl vehicle_colide_final_check_sean(struct Thing *master_vehicle, struct Coord3D *delta);
void __cdecl Setup_Card_System();
char __cdecl load_game();
unsigned __int8 __cdecl srm_CheckCardExists(unsigned __int8 cardno);
unsigned __int8 __cdecl srm_CheckCardFormated(unsigned __int8 cardno);
char __cdecl save_game();
int __cdecl card_event();
int __cdecl clear_event();
void __cdecl Clear_Card_Events_SW();
void __cdecl Clear_Card_Events_HW();
int __cdecl card_event_x();
int __cdecl clear_event_x();
char __cdecl mymemcmp(unsigned __int8 *source1_ptr, unsigned __int8 *source2_ptr, unsigned int check_size);
int __cdecl CheckCardSpace(unsigned __int8 cardno);
unsigned __int8 __cdecl CheckCardExists(unsigned __int8 cardno);
unsigned int __cdecl dir_card(unsigned __int8 cardno, struct DIRENTRY *d);
unsigned int __cdecl test_card_event_SW();
unsigned int __cdecl test_card_event_HW();
int __cdecl CheckCardFile(unsigned __int8 cardno, unsigned __int8 *Fname);
unsigned int __cdecl DeleteCardFile(unsigned __int8 cardno, unsigned __int8 *Fname);
// void _main();
int __fastcall sub_80067B0C(char *a1, char *a2);
// int __fastcall boot(_DWORD, _DWORD); weak
// int __fastcall EnterCriticalSection(_DWORD); weak
// int __fastcall close(_DWORD); weak
// int __fastcall write(_DWORD, _DWORD, _DWORD); weak
// int __fastcall EnableEvent(_DWORD); weak
// int __fastcall erase(_DWORD); weak
// int __fastcall format(_DWORD); weak
// int __fastcall InitHeap(_DWORD, _DWORD); weak
// int __fastcall nextfile(_DWORD); weak
// int __fastcall OpenEvent(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall read(_DWORD, _DWORD, _DWORD); weak
// int __fastcall TestEvent(_DWORD); weak
// int __fastcall open(_DWORD, _DWORD); weak
// int __fastcall firstfile2(_DWORD, _DWORD); weak
// int FlushCache(void); weak
// int __fastcall SetSp(_DWORD); weak
int __fastcall sub_80067D30(int a1);
int sub_80067D88();
// int PAD_dr(void); weak
// int __fastcall PAD_init2(_DWORD, _DWORD); weak
// int __fastcall ChangeClearPAD(_DWORD); weak
int sub_80067E10();
int __fastcall sub_80067E40(int a1, int a2, int a3, int a4);
int sub_80067E70();
int sub_80067EA0();
// int GsGetWorkBase(void); weak
int sub_80067F10();
int __fastcall sub_80068130(int a1, int a2, int a3, int a4);
int __fastcall sub_800681DC(int a1);
// int __fastcall HookEntryInt(_DWORD); weak
// int ExitCriticalSection(void); weak
void sub_800682A8();
// int ReturnFromException(void); weak
int (__fastcall *__fastcall sub_800682C8(int a1, int a2, int a3, int a4))(int a1, int a2, int a3, int a4);
int *__fastcall sub_8006832C(int a1, int a2, int a3, int a4);
int sub_80068384();
int __fastcall sub_800684D4(int a1, int a2, int a3, int a4);
int (*(__fastcall *sub_8006856C())(int (*a1)(void)))(void);
int __fastcall sub_800685E8(int a1, int a2, int a3, int a4);
int (*sub_8006861C())(void);
int (*__fastcall sub_8006866C(int (*a1)(void)))(void);
// int __fastcall ChangeClearRCnt(_DWORD, _DWORD); weak
int __fastcall sub_800686DC(int a1);
int __fastcall sub_800687E0(int a1);
int __fastcall sub_80068868(int a1);
int __fastcall sub_80068890(char a1);
int __fastcall sub_80068B2C(int a1);
// int GsGetWorkBase_0(void); weak
int __fastcall sub_80068BC8(int a1);
int __fastcall sub_80068C08(int a1);
int __fastcall sub_80068C38(unsigned __int8 *a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4);
int __fastcall sub_80068C88(unsigned __int8 *a1, int a2);
int __fastcall sub_80068DC0(int a1, int a2);
int __fastcall sub_80068DF8(int a1);
int __fastcall sub_80068E7C(unsigned __int8 *a1);
int *__fastcall sub_80068ED4(int *a1);
int __fastcall sub_80068FF4(int a1);
unsigned int __fastcall sub_800694E4(int a1, int a2, int a3, __int16 a4, unsigned __int8 *a5);
int __fastcall sub_80069538(int a1, int *a2);
int __fastcall sub_800697DC(int a1, int a2, __int16 a3);
unsigned int __fastcall sub_8006982C(__int16 a1, __int16 a2);
unsigned int __fastcall sub_800698FC(__int16 a1, __int16 a2);
unsigned int __fastcall sub_800699CC(__int16 a1, __int16 a2);
unsigned int __fastcall sub_80069A08(unsigned __int8 *a1);
int __fastcall sub_80069A8C(__int16 *a1);
int sub_80069B64();
int __fastcall sub_80069B7C(int a1, int a2);
int __fastcall sub_80069C64(int a1, int a2);
int __fastcall sub_80069EAC(int *a1, int *a2);
int __fastcall sub_8006A15C(int *a1, _DWORD *a2);
int __fastcall sub_8006A428(unsigned int a1);
int __fastcall sub_8006A460(int a1);
int __fastcall sub_8006A480(int *a1, int a2);
int __fastcall sub_8006A4CC(int a1);
int __fastcall sub_8006A51C(int a1);
int __fastcall sub_8006A550(int a1, unsigned __int8 *a2, int a3);
int __fastcall sub_8006A574(int a1, unsigned __int8 *a2, int a3, int a4);
int sub_8006A760();
int __fastcall sub_8006AA38(int a1);
int __fastcall sub_8006AB88(int a1);
int sub_8006AD0C();
int sub_8006AD2C();
int __fastcall sub_8006ADC8(_BYTE *a1, unsigned __int8 *a2, int a3);
// int __fastcall GPU_cw(_DWORD); weak
int __fastcall sub_8006AE30(char a1, char a2, __int16 a3, __int16 a4);
int __fastcall sub_8006AEC4(int a1, __int16 a2);
unsigned int __fastcall sub_8006AFE4(unsigned int *a1, unsigned int *a2);
int __fastcall sub_8006B098(int a1, int a2);
int __fastcall sub_8006B0E8(int a1);
int __fastcall sub_8006B0FC(int a1);
int __fastcall sub_8006B124(int a1);
int __fastcall sub_8006B160(int a1);
int __fastcall sub_8006B214(int a1);
int __fastcall sub_8006B5E0(int a1, int a2, __int16 a3);
int __fastcall sub_8006B644(int a1, __int16 a2, __int16 a3, __int16 a4, int a5);
int __fastcall sub_8006B6D0(int a1, __int16 a2, __int16 a3, __int16 a4, __int16 a5);
int *__fastcall sub_8006B70C(unsigned __int8 a1);
int __fastcall sub_8006B778(unsigned __int8 a1);
int __fastcall sub_8006B7D4(int a1);
int __fastcall sub_8006B9C4(const char *a1, int a2);
void __fastcall sub_8006BA58(__int16 a1, __int16 a2, char a3, char a4, char a5);
int __fastcall sub_8006BACC(__int16 a1, __int16 a2, char a3, char a4, char a5);
int __fastcall sub_8006BC68(unsigned __int16 a1, unsigned __int16 a2);
int *sub_8006BFB8();
_WORD *__fastcall sub_8006C068(_DWORD *a1, int a2);
int sub_8006C168();
void __fastcall sub_8006C1D8(__int16 a1, __int16 a2, __int16 a3, __int16 a4);
void __fastcall sub_8006C288(int a1);
int __fastcall sub_8006C96C(int a1, int a2, int a3, unsigned int a4);
int __fastcall sub_8006CB28(int a1, int a2, int a3, unsigned int a4);
int __fastcall sub_8006CCF0(int a1, int a2, int a3);
int __fastcall sub_8006CEC8(int a1, int a2, int a3);
// int __fastcall SeVibOn_2(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SetVib_2(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SsUtVibrateOn_2(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SsUtVibrateOff_2(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SeVibOn_3(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SetVib_3(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SsUtVibrateOn_3(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall SsUtVibrateOff_3(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
int __fastcall sub_8006D0E8(int a1);
void __fastcall sub_8006D118(int a1, int a2, unsigned __int16 a3);
int *__fastcall sub_8006DA08(int *a1, int a2);
int __fastcall sub_8006DAD8(__int16 *a1, __int16 a2, __int16 a3, int a4);
int __fastcall sub_8006E318(int *a1, int a2);
int __fastcall sub_8006E458(int a1, int a2);
int *__fastcall sub_8006E5D0(int *a1, int a2);
int __fastcall sub_8006E640(int *a1);
int __fastcall sub_8006E6C0(int a1);
int *__fastcall sub_8006E918(int *a1, int a2);
int *__fastcall sub_8006E9E8(int *a1, int a2);
int __fastcall sub_8006EAB8(_DWORD *a1, int a2, int a3, char a4);
// int gte_init(void); weak
// int __fastcall sub_8006EBC8(_DWORD, _DWORD, _DWORD); weak
int sub_8006EC28();
void sub_8006EC38();
BOOL sub_8006ECD8();
int __fastcall sub_8006EEE8(__int16 *a1, int *a2, int *a3);
// int __fastcall mk_spr_packet(_DWORD, _DWORD, _DWORD); weak
int __fastcall sub_8006F3F0(int a1, int a2);
int *__fastcall sub_8006FA08(int *a1, unsigned __int16 *a2);
_DWORD *__fastcall sub_8006FEC4(int *a1, int *a2, _DWORD *a3);
// int __fastcall SetRotMatrix(_DWORD); weak
// int __fastcall SetTransMatrix(_DWORD); weak
int sub_80070370();
int sub_80070410();
int __fastcall sub_80070658(int _$A0, int _$A1, int _$A2, int _$A3, int a5, int a6, int a7, int a8, int a9, int *a10);
int __fastcall sub_80070904(int _$A0, int _$A1, int _$A2, int a4, int a5, int a6, int a7, _DWORD *a8, _DWORD *a9);
// int __fastcall gte_scope_f3(_DWORD, _DWORD, _DWORD); weak
// int __fastcall gte_scope_tf3(_DWORD, _DWORD, _DWORD); weak
// int __fastcall gte_scope_g3(_DWORD, _DWORD, _DWORD); weak
// int __fastcall gte_scope_tg3(_DWORD, _DWORD, _DWORD); weak
_DWORD *__fastcall sub_80071394(_DWORD *a1, int a2, int a3, int **a4);
_DWORD *__fastcall sub_800714B4(_DWORD *_$A0, int a2, int a3, int **a4);
_DWORD *__fastcall sub_80071764(int _$A0, int a2, int a3, int **a4);
_DWORD *__fastcall sub_80071858(_DWORD *a1, int a2, int a3, int **a4);
_DWORD *__fastcall sub_80071978(_DWORD *_$A0, int a2, int a3, int **a4);
_DWORD *__fastcall sub_80071AB8(_DWORD *a1, int a2, int a3, int **a4);
void __fastcall sub_8007202C(int a1, int a2);
void __fastcall sub_80072044(int _$A0);
void __fastcall sub_80072050(int _$A0);
void __fastcall sub_8007205C(int _$A0);
// int sub_80072188(void); weak
int __fastcall sub_80072470(_DWORD *a1);
unsigned int __fastcall sub_80072600(int _$A0);
int __fastcall sub_80072718(int _$A0, _DWORD *a2, int *a3);
int __fastcall sub_800728E8(int _$A0, int a2, int a3, _DWORD *a4);
int __fastcall sub_80072968(int _$A0, int a2, _DWORD *a3);
void __fastcall sub_80072D04(int *a1, int _$A1);
int __fastcall sub_80072DD8(int a1);
int __fastcall sub_80072E28(unsigned int a1);
int __fastcall sub_80072EE0(int a1);
_BYTE *__fastcall sub_8007355C(_BYTE *a1, char a2, int a3);
// int __fastcall memcpy(_DWORD, _DWORD, _DWORD); weak
char *__fastcall sub_800735CC(char *a1, char *a2);
// int __fastcall setjmp(_DWORD); weak
int __fastcall sub_800736EC(unsigned __int8 *a1);
int __fastcall sub_8007372C(char *a1);
int __fastcall sub_8007376C(char *a1, char *a2);
_BYTE *__fastcall sub_800737DC(_BYTE *a1, unsigned __int8 *a2);
_BYTE *__fastcall sub_8007380C(_BYTE *a1, _BYTE *a2);
char *__fastcall sub_8007388C(char *a1, char *a2, int a3);
int sub_8007390C(int a1, char *a2, ...);
// int __fastcall memchr(_DWORD, _DWORD, _DWORD); weak
// void __fastcall __noreturn exit(_DWORD); weak
int __fastcall sub_800741AC(int a1, unsigned __int8 *a2);
int __fastcall sub_800748AC(unsigned __int8 a1);
int __cdecl _cmpsf2(float a1, float a2);
int __cdecl _cmpdf2(double a1, double a2);
int __fastcall sub_80075E5C(int a1, _BYTE *a2);
int __fastcall sub_80075E7C(int a1, _BYTE *a2);
int __fastcall sub_80075F24(int a1);
int __fastcall sub_80075F3C(int a1);
int __fastcall sub_80075F54(int a1);
int __fastcall sub_80075F6C(unsigned __int8 a1, _BYTE *a2, _BYTE *a3, int a4);
BOOL __fastcall sub_8007608C(unsigned __int8 a1, _BYTE *a2, _BYTE *a3);
BOOL __fastcall sub_800760D8(unsigned __int8 a1, _BYTE *a2, _BYTE *a3);
int __fastcall sub_80076144(int a1, int a2, char a3);
int __fastcall sub_80076218(_BYTE *a1);
_BYTE *__fastcall sub_800762A8(int a1, _BYTE *a2);
int __fastcall sub_800763D4(unsigned __int8 *a1);
int sub_800764C4();
int sub_800764E8();
int __fastcall sub_80076554(int a1, int a2, int a3, int a4);
void __fastcall sub_8007659C(_BYTE *a1, char *a2);
int sub_800765CC();
int sub_800765EC();
int sub_80076684();
int sub_80076758();
int sub_80076828();
int __fastcall sub_80076BEC(int a1, _BYTE *a2);
int __fastcall sub_80076C9C(int a1, _BYTE *a2);
int __fastcall sub_80076D28(unsigned __int8 a1, _BYTE *a2, _BYTE *a3, int a4);
int __fastcall sub_80076FB4(_BYTE *a1);
int sub_80077064();
int __fastcall sub_80077164(int a1, int a2, int a3);
int __fastcall sub_80077288(int a1, _BYTE *a2);
int __fastcall sub_80077344(int a1, int a2);
int __fastcall sub_80077460(int a1, int a2);
int sub_800775A4();
int sub_800776A8();
int sub_800776D0();
int sub_800776F8();
// int __fastcall DeliverEvent(_DWORD, _DWORD); weak
int sub_80077730();
int (*sub_80077738())();
BOOL __fastcall sub_800777B8(_BYTE *a1);
BOOL sub_800777E0();
BOOL __fastcall sub_80077808(_BYTE *a1);
BOOL __fastcall sub_80077844(int a1, int a2, char a3);
// int __fastcall sub_80077878(_DWORD, _DWORD); weak
int __fastcall sub_80077E84(int a1, char *a2);
int __fastcall sub_80077F3C(int a1);
int __fastcall sub_8007820C(_BYTE *a1, unsigned __int8 *a2, int a3);
BOOL __fastcall sub_8007823C(int a1, int a2, int a3);
int __fastcall sub_800782AC(char *a1, char *a2, int a3);
int __fastcall sub_8007832C(unsigned __int8 *a1);
int __fastcall sub_80078350(int a1, unsigned __int8 *a2);
int sub_80078668();
BOOL __fastcall sub_80078870(int a1, unsigned int a2);
void __fastcall sub_80078960(int a1, int a2, int a3);
int sub_80078980();
int __fastcall sub_80079334(int a1, int a2, int a3, int a4, int a5, int a6, int a7);
BOOL __fastcall sub_800794C0(_DWORD *a1, int *a2, unsigned int a3);
int __fastcall sub_80079514(int a1);
int __fastcall sub_8007953C(int a1, int a2, int a3, int a4);
int __fastcall sub_80079C38(int a1);
int __fastcall sub_80079CCC(int a1, unsigned __int16 a2, int a3, unsigned __int16 a4);
int __fastcall sub_80079F18(int *a1, int a2, int a3, __int16 a4);
BOOL sub_8007A2AC();
int sub_8007A43C();
int sub_8007A4BC();
// int __fastcall CloseEvent(_DWORD); weak
// int __fastcall DisableEvent(_DWORD); weak
int __fastcall sub_8007A5DC(int a1);
int sub_8007AB68();
int sub_8007AB9C();
unsigned int __fastcall sub_8007ABC8(__int16 *a1, unsigned int a2);
int __fastcall sub_8007AC30(__int16 *a1, unsigned int a2);
int sub_8007AFA0();
int __fastcall sub_8007B0C0(int a1, unsigned int a2);
int __fastcall sub_8007B328(int a1, unsigned int a2);
BOOL __fastcall sub_8007B4E0(int a1, unsigned int a2, int a3);
BOOL __fastcall sub_8007BEC4(int a1);
// int __fastcall spu_setReverbAttr(_DWORD); weak
int __fastcall sub_8007C518(int *a1);
int __fastcall sub_8007C8B0(int a1);
int sub_8007CA18();
int __fastcall sub_8007CD18(int a1, _DWORD *a2);
int __fastcall sub_8007CD88(int a1);
int __fastcall sub_8007D054(int a1, int a2, int a3);
int __fastcall sub_8007D6D0(int a1);
int __fastcall sub_8007D748(int a1);
BOOL __fastcall sub_8007D874(int a1);
unsigned int __fastcall sub_8007D8C8(unsigned int a1);
unsigned int __fastcall sub_8007D92C(__int16 *a1, unsigned int a2);
int __fastcall sub_8007D98C(int *a1);
int __fastcall sub_8007D9C0(int a1, int a2);
int __fastcall sub_8007DF54(unsigned int a1);
// int __fastcall WaitEvent(_DWORD); weak
// int __fastcall card_load(_DWORD); weak
// int __fastcall card_info(_DWORD); weak
// int __fastcall card_auto(_DWORD); weak
int __fastcall sub_8007E164(int a1);
// int __fastcall card_write(_DWORD, _DWORD, _DWORD); weak
// int __fastcall InitCARD2(_DWORD); weak
// int StartCARD2(void); weak
// int bu_init(void); weak
// int new_card(void); weak
