// Code generated by "stringer -linecomment -type Kind"; DO NOT EDIT.

package sym

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindName1-1]
	_ = x[KindName2-2]
	_ = x[KindName5-5]
	_ = x[KindName6-6]
	_ = x[KindIncSLD-128]
	_ = x[KindIncSLDByte-130]
	_ = x[KindIncSLDWord-132]
	_ = x[KindSetSLD-134]
	_ = x[KindSetSLD2-136]
	_ = x[KindEndSLD-138]
	_ = x[KindFuncStart-140]
	_ = x[KindFuncEnd-142]
	_ = x[KindBlockStart-144]
	_ = x[KindBlockEnd-146]
	_ = x[KindDef-148]
	_ = x[KindDef2-150]
	_ = x[KindOverlay-152]
	_ = x[KindSetOverlay-154]
}

const _Kind_name = "125680828486888a8c8e90929496overlayset overlay"

var _Kind_map = map[Kind]string{
	1:   _Kind_name[0:1],
	2:   _Kind_name[1:2],
	5:   _Kind_name[2:3],
	6:   _Kind_name[3:4],
	128: _Kind_name[4:6],
	130: _Kind_name[6:8],
	132: _Kind_name[8:10],
	134: _Kind_name[10:12],
	136: _Kind_name[12:14],
	138: _Kind_name[14:16],
	140: _Kind_name[16:18],
	142: _Kind_name[18:20],
	144: _Kind_name[20:22],
	146: _Kind_name[22:24],
	148: _Kind_name[24:26],
	150: _Kind_name[26:28],
	152: _Kind_name[28:35],
	154: _Kind_name[35:46],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
